export const SIGN_UP_USER_DATA = "SIGN_UP_USER_DATA" ;
export const USER_LOGIN = "USER_LOGIN";
export const GET_PACKAGES = "GET_PACKAGES";
export const EMAIL_VERIFICATION ="EMAIL_VERIFICATION";
export const PROFILE_DATA = "PROFILE_DATA"