export const GET_ALL_DISTRICTS = "GET_ALL_DISTRICTS";
export const ADD_DISTRICTS = "ADD_DISTRICTS";
export const DELETE_DISTRICTS = "DELETE_DISTRICTS";
export const UPDATE_DISTRICTS = "UPDATE_DISTRICTS";
