export  const GET_DISTRICTS_DATA ="GET_DISTRICTS_DATA" ;
export const   GET_ADMINS_DATA = "GET_ADMINS_DATA" ;
export  const GET_USERS_DATA = "GTE_USERS_DATA";
export const GET_CONST_ANSWER = "GET_CONST_ANSWER";
export const SIGNUP_DATA = "SIGNUP_DATA" ;
export const LOGIN_DATA = "LOGIN_DATA";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const ADMIN_LOGIN_DATA ="ADMIN_LOGIN_DATA";
export const ADMIN_LOGOUT_DATA = "ADMIN_LOGOUT_DATA";
export const EDIT_DIST = "EDIT_DIST" ;
export const DELETE_DIST = "DELETE_DIST";
export const UPDATE_CONSTI = "UPDATE_CONSTI";
export const ADDNEWDIST = "ADDNEWDIST"

