export  const GET_DISTRICTS_DATA ="GET_DISTRICTS_DATA" ;
export const   GET_ADMINS_DATA = "GET_ADMINS_DATA" ;
export  const GET_USERS_DATA = "GTE_USERS_DATA";
export const GET_CONST_ANSWER = "GET_CONST_ANSWER";
export const SIGNUP_DATA = "SIGNUP_DATA" ;
export const LOGIN_DATA = "LOGIN_DATA"

