export const SIGN_UP_USER_DATA = "SIGN_UP_USER_DATA" ;
export const USER_LOGIN = "USER_LOGIN";
export const GET_PACKAGES = "GET_PACKAGES";
export const EMAIL_VERIFICATION ="EMAIL_VERIFICATION";
export const PROFILE_DATA = "PROFILE_DATA";
export const GET_EXAMS_LIST = "GET_EXAMS_LIST";
export const USER_LOG_OUT= "USER_LOG_OUT" ;
export const START_EXAM = "START_EXAM";
export const END_EXAM = "END_EXAM"